before_script:
  - docker info

build_image:
  script:
    - docker volume create viz-dev-dbdata
    - docker build . --rm -t viz-dev
    - docker run viz-dev /home/vizdev/viz-dev-backend/vendor/phpunit/phpunit/phpunit